import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { SafetyCertificateOutlined, EyeOutlined, FileProtectOutlined, MessageOutlined, VideoCameraOutlined, TeamOutlined, CheckCircleOutlined, ArrowRightOutlined, RocketOutlined } from '@ant-design/icons';
import LanguageSelector from '../components/LanguageSelector';
import styles from './landing.module.css';
var LandingPage = function () {
    var t = useTranslation().t;
    var navigate = useNavigate();
    var _a = useState(new Set()), visibleSections = _a[0], setVisibleSections = _a[1];
    var observerRef = useRef(null);
    useEffect(function () {
        // Intersection Observer for animations
        observerRef.current = new IntersectionObserver(function (entries) {
            entries.forEach(function (entry) {
                if (entry.isIntersecting) {
                    setVisibleSections(function (prev) { return new Set(prev).add(entry.target.id); });
                }
            });
        }, { threshold: 0.1 });
        var sections = document.querySelectorAll('[data-section]');
        sections.forEach(function (section) { var _a; return (_a = observerRef.current) === null || _a === void 0 ? void 0 : _a.observe(section); });
        return function () { var _a; return (_a = observerRef.current) === null || _a === void 0 ? void 0 : _a.disconnect(); };
    }, []);
    var features = [
        { icon: _jsx(SafetyCertificateOutlined, {}), key: 0 },
        { icon: _jsx(EyeOutlined, {}), key: 1 },
        { icon: _jsx(FileProtectOutlined, {}), key: 2 },
        { icon: _jsx(MessageOutlined, {}), key: 3 },
        { icon: _jsx(VideoCameraOutlined, {}), key: 4 },
        { icon: _jsx(TeamOutlined, {}), key: 5 }
    ];
    var stats = t('landing.problem.stats', { returnObjects: true });
    return (_jsxs("div", { className: styles.landing, children: [_jsxs("header", { className: styles.header, children: [_jsxs("div", { className: styles.logo, children: [_jsx(SafetyCertificateOutlined, { style: { fontSize: 28 } }), _jsx("span", { children: "InsiderThreat" })] }), _jsx(LanguageSelector, {})] }), _jsxs("section", { id: "hero", "data-section": true, className: "".concat(styles.hero, " ").concat(visibleSections.has('hero') ? styles.visible : ''), children: [_jsx("div", { className: styles.heroBackground }), _jsxs("div", { className: styles.heroContent, children: [_jsx("h1", { className: styles.heroTitle, children: t('landing.hero.title') }), _jsx("p", { className: styles.heroSubtitle, children: t('landing.hero.subtitle') }), _jsxs("div", { className: styles.heroCta, children: [_jsxs("button", { className: styles.btnPrimary, onClick: function () { return navigate('/login'); }, children: [t('landing.hero.cta_primary'), _jsx(RocketOutlined, {})] }), _jsx("button", { className: styles.btnSecondary, children: t('landing.hero.cta_secondary') })] })] })] }), _jsx("section", { id: "problem", "data-section": true, className: "".concat(styles.section, " ").concat(visibleSections.has('problem') ? styles.visible : ''), children: _jsxs("div", { className: styles.container, children: [_jsx("h2", { className: styles.sectionTitle, children: t('landing.problem.title') }), _jsx("p", { className: styles.sectionDescription, children: t('landing.problem.description') }), _jsx("div", { className: styles.statsGrid, children: stats.map(function (stat, index) { return (_jsxs("div", { className: styles.statCard, children: [_jsx("div", { className: styles.statValue, children: stat.value }), _jsx("div", { className: styles.statLabel, children: stat.label })] }, index)); }) })] }) }), _jsx("section", { id: "features", "data-section": true, className: "".concat(styles.section, " ").concat(styles.featuresSection, " ").concat(visibleSections.has('features') ? styles.visible : ''), children: _jsxs("div", { className: styles.container, children: [_jsx("h2", { className: styles.sectionTitle, children: t('landing.features.title') }), _jsx("p", { className: styles.sectionSubtitle, children: t('landing.features.subtitle') }), _jsx("div", { className: styles.featuresGrid, children: features.map(function (feature, index) {
                                var item = t("landing.features.items.".concat(index), { returnObjects: true });
                                return (_jsxs("div", { className: styles.featureCard, children: [_jsx("div", { className: styles.featureIcon, children: feature.icon }), _jsx("h3", { className: styles.featureTitle, children: item.title }), _jsx("p", { className: styles.featureDescription, children: item.description })] }, feature.key));
                            }) })] }) }), _jsx("section", { id: "how-it-works", "data-section": true, className: "".concat(styles.section, " ").concat(visibleSections.has('how-it-works') ? styles.visible : ''), children: _jsxs("div", { className: styles.container, children: [_jsx("h2", { className: styles.sectionTitle, children: t('landing.howItWorks.title') }), _jsx("div", { className: styles.stepsTimeline, children: [0, 1, 2, 3].map(function (index) {
                                var step = t("landing.howItWorks.steps.".concat(index), { returnObjects: true });
                                return (_jsxs("div", { className: styles.stepCard, children: [_jsx("div", { className: styles.stepNumber, children: index + 1 }), _jsx("h3", { className: styles.stepTitle, children: step.title }), _jsx("p", { className: styles.stepDescription, children: step.description })] }, index));
                            }) })] }) }), _jsx("section", { id: "benefits", "data-section": true, className: "".concat(styles.section, " ").concat(visibleSections.has('benefits') ? styles.visible : ''), children: _jsxs("div", { className: styles.container, children: [_jsx("h2", { className: styles.sectionTitle, children: t('landing.benefits.title') }), _jsx("div", { className: styles.benefitsGrid, children: [0, 1, 2, 3, 4, 5].map(function (index) {
                                var benefit = t("landing.benefits.items.".concat(index), { returnObjects: true });
                                return (_jsxs("div", { className: styles.benefitCard, children: [_jsx(CheckCircleOutlined, { className: styles.benefitIcon }), _jsx("h3", { className: styles.benefitTitle, children: benefit.title }), _jsx("p", { className: styles.benefitDescription, children: benefit.description })] }, index));
                            }) })] }) }), _jsx("section", { id: "testimonials", "data-section": true, className: "".concat(styles.section, " ").concat(styles.testimonialsSection, " ").concat(visibleSections.has('testimonials') ? styles.visible : ''), children: _jsxs("div", { className: styles.container, children: [_jsx("h2", { className: styles.sectionTitle, children: t('landing.testimonials.title') }), _jsx("div", { className: styles.testimonialsGrid, children: [0, 1, 2].map(function (index) {
                                var testimonial = t("landing.testimonials.items.".concat(index), { returnObjects: true });
                                return (_jsxs("div", { className: styles.testimonialCard, children: [_jsxs("div", { className: styles.quote, children: ["\"", testimonial.quote, "\""] }), _jsxs("div", { className: styles.author, children: [_jsx("div", { className: styles.authorName, children: testimonial.name }), _jsx("div", { className: styles.authorRole, children: testimonial.role })] })] }, index));
                            }) })] }) }), _jsx("section", { id: "pricing", "data-section": true, className: "".concat(styles.section, " ").concat(visibleSections.has('pricing') ? styles.visible : ''), children: _jsxs("div", { className: styles.container, children: [_jsx("h2", { className: styles.sectionTitle, children: t('landing.pricing.title') }), _jsx("p", { className: styles.sectionSubtitle, children: t('landing.pricing.subtitle') }), _jsx("div", { className: styles.pricingGrid, children: [0, 1, 2].map(function (index) {
                                var plan = t("landing.pricing.plans.".concat(index), { returnObjects: true });
                                return (_jsxs("div", { className: "".concat(styles.pricingCard, " ").concat(plan.popular ? styles.popularPlan : ''), children: [plan.popular && _jsx("div", { className: styles.popularBadge, children: "POPULAR" }), _jsx("h3", { className: styles.planName, children: plan.name }), _jsxs("div", { className: styles.planPrice, children: [plan.price, plan.period && _jsxs("span", { className: styles.planPeriod, children: ["/", plan.period] })] }), _jsx("p", { className: styles.planDescription, children: plan.description }), _jsx("ul", { className: styles.planFeatures, children: plan.features.map(function (feature, fIndex) { return (_jsxs("li", { children: [_jsx(CheckCircleOutlined, {}), feature] }, fIndex)); }) }), _jsxs("button", { className: plan.popular ? styles.btnPrimary : styles.btnSecondary, children: [t('common.getStarted'), _jsx(ArrowRightOutlined, {})] })] }, index));
                            }) })] }) }), _jsx("section", { id: "cta", "data-section": true, className: "".concat(styles.section, " ").concat(styles.ctaSection, " ").concat(visibleSections.has('cta') ? styles.visible : ''), children: _jsxs("div", { className: styles.ctaContent, children: [_jsx("h2", { className: styles.ctaTitle, children: t('landing.cta.title') }), _jsx("p", { className: styles.ctaSubtitle, children: t('landing.cta.subtitle') }), _jsxs("button", { className: styles.btnPrimary, onClick: function () { return navigate('/login'); }, children: [t('landing.cta.button'), _jsx(RocketOutlined, {})] })] }) }), _jsx("footer", { className: styles.footer, children: _jsxs("div", { className: styles.container, children: [_jsxs("div", { className: styles.footerGrid, children: [_jsxs("div", { className: styles.footerBrand, children: [_jsxs("div", { className: styles.footerLogo, children: [_jsx(SafetyCertificateOutlined, { style: { fontSize: 32 } }), _jsx("span", { children: t('landing.footer.company') })] }), _jsx("p", { className: styles.footerTagline, children: t('landing.footer.tagline') })] }), _jsxs("div", { className: styles.footerLinks, children: [_jsx("h4", { children: t('landing.footer.links.product') }), _jsxs("ul", { children: [_jsx("li", { children: _jsx("a", { href: "#features", children: t('landing.footer.links.solutions') }) }), _jsx("li", { children: _jsx("a", { href: "#pricing", children: t('landing.footer.links.pricing') }) }), _jsx("li", { children: _jsx("a", { href: "#docs", children: t('landing.footer.links.docs') }) })] })] }), _jsxs("div", { className: styles.footerLinks, children: [_jsx("h4", { children: t('landing.footer.links.about') }), _jsxs("ul", { children: [_jsx("li", { children: _jsx("a", { href: "#blog", children: t('landing.footer.links.blog') }) }), _jsx("li", { children: _jsx("a", { href: "#careers", children: t('landing.footer.links.careers') }) }), _jsx("li", { children: _jsx("a", { href: "#contact", children: t('landing.footer.links.contact') }) })] })] }), _jsxs("div", { className: styles.footerLinks, children: [_jsx("h4", { children: t('common.language') }), _jsx(LanguageSelector, {})] })] }), _jsxs("div", { className: styles.footerBottom, children: [_jsx("p", { children: t('landing.footer.copyright') }), _jsxs("div", { className: styles.footerLegal, children: [_jsx("a", { href: "#privacy", children: t('landing.footer.legal.privacy') }), _jsx("a", { href: "#terms", children: t('landing.footer.legal.terms') }), _jsx("a", { href: "#security", children: t('landing.footer.legal.security') })] })] })] }) })] }));
};
export default LandingPage;
